### ISSUE TITLE
Update Japanese language  content by 2/24

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#923] opened 2021-02-22 21:09 UTC
The existing Japanese language site will be frozen on 2/23 so we'll want to do one final content update from the proxy site to pull in all the JP content and ensure the new site gets the most current JP content. 

### XML

https://docs.newrelic.com/translation-index/content/japanese/completed <= those are the straight articles
https://docs.newrelic.com/translation-index/taxonomy/japanese/completed <= landing pages and taxonomy

**Comment by jerelmiller** [comment] 2021-02-22 21:15
FYI, this will happen along with our full content migration, as we pull in the jp content for all pages that have an associated japanese page. We don't do anything separate.

I'd say this is a duplicate of #874. Thoughts?

**Comment by jpvajda** [comment] 2021-02-22 21:30
AH ok! I thought we captured it already.... but I'll specify in #874 that it includes the JP content.

**Closed** 2021-02-22 21:31 UTC
Labels: duplicate, estimation needed, localization, localization-jp
