### ISSUE TITLE
Data Definition Difficult to Obtain

### ISSUE THREAD

**Issue by philn5d-ar** [newrelic/docs-website#2351] opened 2021-05-19 15:37 UTC
### Tell us more about your feedback

Sorry to hear this doc wasn't helpful, but we'd love to make it better! We've 
recorded your feedback. Help us improve this content by providing more info:

* How can we improve this doc?

Make it easier to get to the definition of a specific metric. Currently, I want to know what scale PageHide metric is (ms, s, m) but in order to do so I need to: 1) open data dictionary page (because it doesn't say in New Relic One Data Explorer or Query Builder). 2) figure out which drop down values to select. 3) go through all the options until I finally find the one I'm looking for. Spent quite a few minutes so far looking for something that should be easily accessible (either a link to the definition from the Explorer/Query, a way to just look it up from there, or maybe a search function).

### Doc information (don't delete this section)

* https://docs.newrelic.com/attribute-dictionary/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by paperclypse** [comment] 2021-05-19 18:27
Hi @philn5d-ar! Thanks for writing in. Your suggestion is a good one. I agree that there are a few too many steps to get to a specific data dictionary metric. I don't have an immediate solution for you, but I'll do some digging and get back to you.

**Comment by paperclypse** [comment] 2021-05-19 18:30
It looks like we have an open issue related to adding a search field to the data dictionary page. The issue is #626. I've added your issue there. Feel free to chime in on that issue, if you like.

**Comment by paperclypse** [comment] 2021-05-19 18:32
If you feel like #626 would address your issue, @philn5d-ar, I'll close this one as a duplicate. Thanks!

**Closed** 2021-05-21 16:32 UTC
Labels: external
