### ISSUE TITLE
Japanese landing pages were not imported.

### ISSUE THREAD

**Issue by jmiraNR** [newrelic/docs-website#1236] opened 2021-03-08 23:26 UTC
### Description

Landing pages such as [https://docs.newrelic.com/docs/agents/c-sdk/](https://docs.newrelic.com/docs/agents/c-sdk/) were not imported.

### Steps to reproduce

1. Go to [https://docs.newrelic.com/docs/agents/c-sdk/](https://docs.newrelic.com/docs/agents/c-sdk/)
2. Switch to Japanese
3. Page is in English on the /jp/ site

### Expected behavior

All translated landing pages are imported.

### Screenshots

N/A

### Additional context

See attachment for list.
[Taxonomy and LPs.xlsx](https://github.com/newrelic/docs-website/files/6104750/Taxonomy.and.LPs.xlsx)
[Completed pages.txt](https://github.com/newrelic/docs-website/files/6104751/Completed.pages.txt)
[Completed taxonomy and LP.txt](https://github.com/newrelic/docs-website/files/6104752/Completed.taxonomy.and.LP.txt)

### Environment

N/A

**Comment by jpvajda** [comment] 2021-03-09 14:48
@jmiraNR have you seen other pages like this? It be helpful to know which ones have a similar issue, so perhaps you can run through them and check for us. Also, what are the attachments for?  cc @caylahamann

**Comment by jpvajda** [comment] 2021-03-09 21:44
Looking at the count of pages in  Completed pages.txt it's a significant amount of pages, so we may have do this on our own.

**Comment by jmiraNR** [comment] 2021-03-09 22:25
@jpvajda @zstix We can just wait for the next migration (there is a ticket for it) and do it then. I'm guessing some time next week. these pages are not critical to migrate them now and then again next week.

**Comment by zstix** [comment] 2021-03-09 23:20
@jmiraNR I'm not sure I follow. We are no longer doing "migrations". The new site _should_ have all the content that the old site had. We're going to find these missing pages, but we should be doing any full-site migrations at this point.

**Comment by jpvajda** [comment] 2021-03-09 23:36
@zstix he may be referring to this issue: https://github.com/newrelic/docs-website/issues/994

but to your point, it's not a migration.

**Comment by roadlittledawn** [comment] 2021-03-10 19:07
i _think_ this may be have been caused by the fact that the `docUrl` that came back in migration API JSON didn't quite match where the pages lived on the japanese site, so when we scraped that content, fetches to those pages wouldn't be found. in Drupal, a taxonomy page (with the url you'd expect) went and grabbed the authored content from a node (that had a different URL that wasn't exposed on the front end), so the migration API used that URL instead.

## Example
The .NET agent landing page data came back with a `docUrl` value of: 

    https://docs-dev.newrelic.com/docs/agents/net-agent/net-agent-landing-page. 

The page where this content was ultimately displayed was: 

    https://docs-dev.newrelic.com/docs/agents/net-agent

**Comment by roadlittledawn** [comment] 2021-03-11 14:18
@jpvajda . yeah was thinking we could update the migration script to chop off the end of landing page URLs before fetching the jp version of each. then run an abbreviated  (and shorten all other content types to 1 page)  migration script, sift through the changed files and commit the relevant ones.

**Comment by jpvajda** [comment] 2021-03-11 17:28
@roadlittledawn we should probably discuss I think we were not planning on doing any more migration of data so I'll defer to @zstix if we can this approach! Thanks.

**Comment by zstix** [comment] 2021-03-11 21:30
I've compiled a list of pages from those files and there are *421* unique URLs. I find it hard to believe we're missing _that_ many pages. I assume this is the list of _all_ the pages that we _expect_ to be translated - is this correct, @jmiraNR?

If so, we'll need to determine which pages out of this list we're missing. Here's the list: https://gist.github.com/zstix/a5db7ba10fdfe2a6881c250a338d8599

**Comment by zstix** [comment] 2021-03-11 23:26
I [created a script](https://github.com/newrelic/docs-website/blob/331c7ccad0a90a3b6fabe0998c75b79977a39ce7/scripts/utils/migrate/find-missing-jp-content.js) to find all the missing pages. What it does is take all the pages we _expect_ and does the following:
1. Finds the english MDX file
2. Removes any pages that are automatically generated (list of links)
3. Removes any pages that have _different_ content in the Japanese MDX file

Here's the results. @jmiraNR are there any other pages that we're missing besides these?

```json
[
  "/src/content/docs/agents/c-sdk/index.mdx",
  "/src/content/docs/agents/net-agent/net-agent-api/index.mdx",
  "/src/content/docs/agents/php-agent/php-agent-api/index.mdx",
  "/src/content/docs/agents/python-agent/python-agent-api/index.mdx",
  "/src/content/docs/mobile-monitoring/new-relic-mobile-android/android-sdk-api/index.mdx",
  "/src/content/docs/mobile-monitoring/new-relic-mobile-ios/ios-sdk-api/index.mdx",
  "/src/content/docs/using-new-relic/welcome-new-relic/index.mdx"
]
```

**Comment by jmiraNR** [comment] 2021-03-12 01:20
Hi @zstix. I highlighted in the XLS file that only a few pages are actual landing pages. The rest of the pages are table of content and should be left alone since we create those differently in GH and that works as far as I could test. My issue was really about the landing pages. thx

**Comment by roadlittledawn** [comment] 2021-03-18 23:35
fyi. these pages aren't really landing pages but they're special templated pages for agent API index pages. the text at the top before the methods and their descriptions are in index.mdx files. but the method short descriptions are stored in each method's frontmatter field `shortDescription`. each method has its own file/page, and in previous site method pages were not translated.
* https://jajp-newrelic-docs.onelink-translations.com/docs/agents/net-agent/net-agent-api
* https://jajp-newrelic-docs.onelink-translations.com/docs/agents/php-agent/php-agent-api
* https://jajp-newrelic-docs.onelink-translations.com/docs/agents/python-agent/python-agent-api
* https://jajp-newrelic-docs.onelink-translations.com/docs/mobile-monitoring/new-relic-mobile-android/android-sdk-api
* https://jajp-newrelic-docs.onelink-translations.com/docs/mobile-monitoring/new-relic-mobile-ios/ios-sdk-api

since we did some IA changes and what not, i think this page now has a landing page so it doesn't quite match 1:1 with gatsby version
* OneLink: https://jajp-newrelic-docs.onelink-translations.com/docs/using-new-relic/welcome-new-relic
* Gatsby: https://docs.newrelic.com/docs/using-new-relic/welcome-new-relic/

**Comment by jpvajda** [comment] 2021-03-18 23:40
@roadlittledawn Thanks for the recap. D you have a suggestion of what to do with this content?

**Comment by roadlittledawn** [comment] 2021-03-19 00:34
> @roadlittledawn Thanks for the recap. D you have a suggestion of what to do with this content?

*re: agent API index pages*. we _could_ migrate over (either by hand which isn't too hard or some other way) the content at the top of API index pages, but the way we set up that template requires .mdx files to be in the directory with the index.mdx file. so the translated index.mdx files would also need translated .mdx files for each method as well, otherwise it does not show a list of method names and their descriptions like this:
<img width="1633" alt="2021-03-18_17-25-18" src="https://user-images.githubusercontent.com/2952843/111714606-37622d00-880f-11eb-89bf-1acc56903e45.png">

*re: the welcome-new-relic page*. not really sure about that one. that current landing page looks dated to me. may want to ask @austin-schaefer or @jmiraNR if we want to translate that one. like i said, the onelink version is just a menu page (which we display jp titles for if they exist automatically). not sure if there's an old landing page that matches this current one English one or if we want to translate it anew.

**Comment by jpvajda** [comment] 2021-03-19 17:44
We are meeting with @jmiraNR  about some other JP site things on monday I'll include this topic.

**Comment by roadlittledawn** [comment] 2021-03-19 18:39
@jpvajda you / he may also want to take a good look at the `src/i18n` .mdx files and if there's any that are English only, we need to get the translations for those. for time being, they will show up in searches because the site thinks they're translated so we allow swiftype to index them.

**Comment by roadlittledawn** [comment] 2021-03-24 21:25
scanned the `src/i18n/content/jp` directory and found 47 English files. list here: https://gist.github.com/roadlittledawn/c604ea323077953a7e88c6e1b47d0634

**Comment by jpvajda** [comment] 2021-03-24 21:41
After some digging we've found the issue with these pages, but don't know exactly what might of went wrong during the migration so we propose the following:

`1`. We'll fix the page for which we have JP content for:  C SDK landing
`2`. We'd like to use smartling to translate the English files found in src/il8n. For time being, they will show up in searches because the site thinks they're translated so we allow swiftype to index them.
`3`. Once we have the translated files for those pages we can resolve the discrepancies. 

`As a note`: it's not clear why the migration didn't process these correctly but instead dropped the files as English in the `src/il8n`, instead of spending time on figuring out why, or trying to get content From onelink, we'd like to propose just sending this of to smartling for translation. 

Here is a list of the 47 files we'd need to translate:

```
src/i18n/content/jp/docs/accounts/accounts-billing/account-structure/mastersub-account-structure.mdx
src/i18n/content/jp/docs/accounts/install-new-relic/account-setup/use-multiple-accounts.mdx
src/i18n/content/jp/docs/agents/c-sdk/install-configure/docker-other-container-environments-install-c-sdk.mdx
src/i18n/content/jp/docs/agents/manage-apm-agents/agent-data/link-your-applications-kubernetes.mdx
src/i18n/content/jp/docs/agents/net-agent/other-installation/install-net-agent-aspnet-core.mdx
src/i18n/content/jp/docs/agents/net-agent/other-installation/install-net-agent-windows-communication-foundation-wcf.mdx
src/i18n/content/jp/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/apm-metric-alert-conditions.mdx
src/i18n/content/jp/docs/apis/nerdgraph/examples/nerdgraph-tagging-api-tutorial.mdx
src/i18n/content/jp/docs/apm/new-relic-apm/maintenance/disable-apm-agent.mdx
src/i18n/content/jp/docs/browser/index.mdx
src/i18n/content/jp/docs/full-stack-observability/instrument-everything/instrument-core-services-applications/cloud-services-integrations.mdx
src/i18n/content/jp/docs/full-stack-observability/observe-everything/get-started/get-started-full-stack-observability.mdx
src/i18n/content/jp/docs/infrastructure/install-infrastructure-agent/configuration/config-file-template-newrelic-infrayml.mdx
src/i18n/content/jp/docs/infrastructure/install-infrastructure-agent/get-started/install-infrastructure-agent.mdx
src/i18n/content/jp/docs/infrastructure/install-infrastructure-agent/linux-installation/azure-extensions-infrastructure.mdx
src/i18n/content/jp/docs/infrastructure/install-infrastructure-agent/linux-installation/docker-instrumentation-infrastructure-monitoring.mdx
src/i18n/content/jp/docs/infrastructure/install-infrastructure-agent/manage-your-agent/troubleshoot-running-infrastructure-agent.mdx
src/i18n/content/jp/docs/infrastructure/index.mdx
src/i18n/content/jp/docs/insights/index.mdx
src/i18n/content/jp/docs/integrations/host-integrations/host-integrations-list/vmware-tanzu-monitoring-integration.mdx
src/i18n/content/jp/docs/integrations/kubernetes-integration/get-started/introduction-kubernetes-integration.mdx
src/i18n/content/jp/docs/integrations/kubernetes-integration/link-your-applications/link-your-applications-kubernetes.mdx
src/i18n/content/jp/docs/integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-advanced-configuration.mdx
src/i18n/content/jp/docs/licenses/index.mdx
src/i18n/content/jp/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/aws-lambda-sending-logs-s3.mdx
src/i18n/content/jp/docs/logs/log-management/get-started/get-started-log-management.mdx
src/i18n/content/jp/docs/logs/log-management/ui-data/built-log-parsing-rulesets.mdx
src/i18n/content/jp/docs/mobile-monitoring/index.mdx
src/i18n/content/jp/docs/new-relic-one/use-new-relic-one/build-new-relic-one/build-custom-new-relic-one-application.mdx
src/i18n/content/jp/docs/new-relic-one/use-new-relic-one/core-concepts/new-relic-explorer-view-performance-across-apps-services-hosts.mdx
src/i18n/content/jp/docs/security/security-privacy/compliance/data-encryption.mdx
src/i18n/content/jp/docs/security/security-privacy/data-privacy/data-privacy-new-relic.mdx
src/i18n/content/jp/docs/security/index.mdx
src/i18n/content/jp/docs/serverless-function-monitoring/aws-lambda-monitoring/ui-data/understand-lambda-data-structure.mdx
src/i18n/content/jp/docs/synthetics/synthetic-monitoring/private-locations/containerized-private-minion-cpm-configuration.mdx
src/i18n/content/jp/docs/synthetics/synthetic-monitoring/private-locations/containerized-private-minion-cpm-maintenance-monitoring.mdx
src/i18n/content/jp/docs/synthetics/synthetic-monitoring/private-locations/install-containerized-private-minions-cpms.mdx
src/i18n/content/jp/docs/synthetics/synthetic-monitoring/private-locations/verified-script-execution-private-locations.mdx
src/i18n/content/jp/docs/synthetics/synthetic-monitoring/using-monitors/monitor-downtimes-disable-monitoring-during-scheduled-maintenance-times.mdx
src/i18n/content/jp/docs/synthetics/synthetic-monitoring/using-monitors/store-secure-credentials-scripted-browsers-api-tests.mdx
src/i18n/content/jp/docs/synthetics/synthetic-monitoring/using-monitors/synthetic-monitoring-response-codes.mdx
src/i18n/content/jp/docs/synthetics/index.mdx
src/i18n/content/jp/docs/telemetry-data-platform/get-data/apis/query-metric-data-type.mdx
src/i18n/content/jp/docs/telemetry-data-platform/ingest-manage-data/ingest-apis/introduction-metric-api.mdx
src/i18n/content/jp/docs/telemetry-data-platform/ingest-manage-data/ingest-apis/telemetry-sdks-report-custom-telemetry-data.mdx
src/i18n/content/jp/docs/telemetry-data-platform/ingest-manage-data/understand-data/introduction-querying-new-relic-data.mdx
src/i18n/content/jp/docs/understand-dependencies/distributed-tracing/trace-api/introduction-trace-api.md
```

**Comment by jpvajda** [comment] 2021-03-24 22:10
@jmiraNR and I chatted he's going to look into a few things before making the call on this, moving to blocked until we hear back

**Comment by jpvajda** [comment] 2021-03-25 17:44
We discussed actually closing this issue out and working from this one. They are very related. We can grab that missing translated content that is available to us from the old site, any missing jp content will be identified in this issue: : https://github.com/newrelic/docs-website/issues/994

**Closed by jpvajda** 2021-03-25 17:44 UTC
Labels: P3, blocked, bug, eng, sp:3
