### ISSUE TITLE
right rail navigation anchor links are broken

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#493] opened 2020-12-29 18:53 UTC
### Issue 

I noticed on this page  and a few others the right rail header nav anchors seem to be not working on some links. 

example pages: 

https://docs-preview.newrelic.com/docs/integrations/kubernetes-integration/installation/kubernetes-integration-install-configure#custom-m[…]manifest

https://docs-preview.newrelic.com/docs/integrations/amazon-integrations/get-started/connect-aws-infrastructure#regional-support-availability

perhaps it has something to do with the header anchor linking we added to the page

### expected behavior

The right rail allows a user to click on each nav anchor and the page reflects the users click by moving to that section of the page. 
<img width="413" alt="Screen Shot 2020-12-29 at 11 55 27 AM" src="https://user-images.githubusercontent.com/1395158/103307243-d6277c00-49cc-11eb-8f1f-83205636f0f9.png">

**Comment by jerelmiller** [comment] 2021-01-04 19:02
Possible duplicate of #443

**Comment by jerelmiller** [comment] 2021-01-04 19:03
Nevermind, confirmed this is different. It looks like the table of contents links are not using the custom ID, but rather the generated one.

**Closed** 2021-01-04 21:55 UTC
Labels: P2, bug, catch-all
