### ISSUE TITLE
Issue: CodeStream GitLab custom queries not work

### ISSUE THREAD

**Issue by meded90** [newrelic/docs-website#5038] opened 2021-11-24 15:43 UTC
![WebStorm2021 3 – External Tools xml 2021-11-24 18-39-59](https://user-images.githubusercontent.com/1769500/143269193-d9b5dcec-72e6-4463-9193-10e4de65bd6d.jpg)

some queries always throw an error
`Missing required qualifier.`

remove validation for gitlab requests. or make the save button available after "Test Query"

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/codestream/codestream-ui-overview/pull-requests-section/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by planteater** [comment] 2021-11-30 14:02
Duplicate of https://github.com/TeamCodeStream/codestream/issues/781

**Comment by urbiz-nr** [comment] 2021-11-30 14:41
Closing via Codestream's 781.

**Closed by urbiz-nr** 2021-11-30 14:41 UTC
Labels: content, from_external, pg_codestream
