### ISSUE TITLE
Center-aligned column text is difficult to skim

### ISSUE THREAD

**Issue by barbnewrelic** [newrelic/docs-website#879] opened 2021-02-16 23:05 UTC
## Description

In Drupal, table columns are top-aligned. In the new Docs Site, they are center-aligned. This makes it hard to read.

## Steps to Reproduce

This is across the site, but for example:
Compare
https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/rest-api-alerts/rest-api-calls-alerts#data
with
https://docs-preview.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/rest-api-alerts/rest-api-calls-alerts#data

Or even worse, compare the table in
https://docs.newrelic.com/docs/apis/rest-api-v2/basic-functions/extract-metric-timeslice-data#time
with the table in
https://docs-preview.newrelic.com/docs/apis/rest-api-v2/basic-functions/extract-metric-timeslice-data#time
## Expected Behavior

Maybe it's just me, but having text aligned at the top is much easier to skim across columns and rows.

## Relevant Logs / Console output

n/a

## Additional context

[NOTE]: # (PLEASE DO NOT DELETE THIS SECTION. This contains useful information for the team.)

### Page
https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/rest-api-alerts/rest-api-calls-alerts

### Environment
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by austin-schaefer** [comment] 2021-02-17 22:31
@jpvajda : Not a launch-blocker, but I'd love to get this cosmetic issue fixed by launch if possible.

**Comment by jpvajda** [comment] 2021-02-17 22:44
I actually don't see this as a problem, I'm staring at both pages, and really see little difference, perhaps providing screenshots of where the issue is would help explain why this is an issue.

**Comment by barbnewrelic** [comment] 2021-02-17 23:01
Here's another example.

**Comment by austin-schaefer** [comment] 2021-02-26 06:16
I'd really like to fix this, it's general readability / docs best practice to have text top-align by efault default in tables. Example of where it doesn't look great

![Uploading image.png…]()

**Comment by jerelmiller** [comment] 2021-02-26 08:02
Got a PR up to address this: https://github.com/newrelic/gatsby-theme-newrelic/pull/290

Will get this deployed the next time we update the theme.

**Closed** 2021-02-26 18:01 UTC
Labels: bug, eng, site-cutover

**Comment by austin-schaefer** [comment] 2021-02-26 21:26
Wooo, thanks @jerelmiller ! @barbnewrelic the site will soon be usable again. ;)

**Comment by jerelmiller** [comment] 2021-02-26 21:54
It _just_ went live. Check it out!! https://docs-preview.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/rest-api-alerts/rest-api-calls-alerts#data
