### ISSUE TITLE
Query Builder `Basic mode` is not using the new data dictionary service to return attributes

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#1869] opened 2021-04-16 19:23 UTC
### Steps to Reproduce 

1. Go into the Nr1 Platform > Query Your Data . 
2. On the Query Builder click the Basic button in right corner 
3. Enter in: SyntheticCheck: timepstamp,
4. View the hover text
5. Click on the see attributes in docs link
6. notice the text is different

### Expected 

This part of the Query Builder uses the new data dictionary service to return attributes that are maintained in our docs site repo so all attributes are consistent across both query builder views `NRQL` &  `Basic`.

### Screen shots 

<img width="1526" alt="Screen Shot 2021-04-16 at 12 53 10 PM" src="https://user-images.githubusercontent.com/1395158/115074876-84412e00-9eb7-11eb-83ec-e7c4344b5465.png">

**Comment by zstix** [comment] 2021-04-16 20:12
The definition being displayed in the Query Builder is accurate, it's the link that is producing something wrong. The definition you are seeing when you click on the docs site link is actually for `duration`, not `timestamp`. This is caused by [this bug](https://github.com/newrelic/docs-website/issues/1670).

[Here's another duplicate issue](https://github.com/newrelic/docs-website/issues/1855) that was created for a similar experience. I'm going to close this issue out as well.

**Closed by zstix** 2021-04-16 20:12 UTC
Labels: P3, bug, deven services
