### ISSUE TITLE
Feedback: Create, edit, or find an alert policy

### ISSUE THREAD

**Issue by chrishristov** [newrelic/docs-website#2133] opened 2021-05-05 19:38 UTC
New alert policy button/link is not available on the page and my account is Full access user. The site is slow and such issues are extremely frustrating.
<img width="1389" alt="newrelic-issue" src="https://user-images.githubusercontent.com/9422654/117199205-88be7f80-adaf-11eb-938d-f07e29177241.png">

**Comment by dbarnesbrownNR** [comment] 2021-05-05 20:06
@chrishristov thank you for your feedback! This certainly does sound frustrating. It appears to be more of a UI issue than a docs issue, however, and I am unable to reproduce the issue personally, so I will raise it with the appropriate team.

**Comment by dbarnesbrownNR** [comment] 2021-05-05 22:23
Hi @chrishristov, looks like this is likely related to your user permissioning. I've reached out to the correct team at New Relic and they'd like to help you out. Would you start by filing a support ticket with them at [https://support.newrelic.com/](https://support.newrelic.com/)? I don't have the ability to look up your user info from GitHub, but if you use that route you'll be able to select the right options and file using your user identity on New Relic. Thanks!

**Comment by dbarnesbrownNR** [comment] 2021-05-05 22:24
Closing as this has been referred to New Relic Support engineers per above comment.

**Closed by dbarnesbrownNR** 2021-05-05 22:24 UTC
Labels: bug, external
