### ISSUE TITLE
Remove References to Mobile Push Notifications

### ISSUE THREAD

**Issue by tariqahmed** [newrelic/docs-website#1643] opened 2021-04-01 00:35 UTC
With the V2 User Model, Mobile Push Notifications are no longer available. However there are many references throughout the site which do reference it.

Essentially we need to remove all references of this ability:
https://docs.newrelic.com/?q=push%20notifications&size=n_10_n

See the following for more details on when this may become available in the future:
https://newrelic.atlassian.net/browse/CF-4856

**Comment by austin-schaefer** [comment] 2021-04-01 00:52
Possible duplicate of #1634 ?

**Comment by austin-schaefer** [comment] 2021-04-01 00:52
If we need to do this across the site, we'll probably need a DOC Jira for it so we can bring it into a sprint.

**Comment by zuluecho9** [comment] 2021-04-01 14:16
Affirmative, will create that.

**Comment by tariqahmed** [comment] 2021-04-01 14:19
Yup... dupe of #1634, can close this one.

**Closed** 2021-04-01 14:20 UTC
Labels: content

**Comment by zuluecho9** [comment] 2021-04-01 14:22
Created this https://newrelic.atlassian.net/browse/DOC-6704.
