### ISSUE TITLE
Middle column cuts off table

### ISSUE THREAD

**Issue by wrekone** [newrelic/docs-website#2290] opened 2021-05-13 21:43 UTC
### Description

When looking at a page that has three columns,  if I make the browser window exactly half the width of my screen, words get cut off by the formatting of the middle column. If the browser window is any bigger or smaller than 50% of the screen width, the words wrap correctly. I have only tested this on a 3840 × 2160 monitor.

### Steps to reproduce

1. Go to https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/alert-notifications/muting-rules-suppress-notifications/#manage-with-nerdgraph
2. Scroll down to the table of muting rules definitions.
3. Resize the window to 50% of monitor width.
4. See text cut off on the right side of the middle column.

### Expected behavior

The text should wrap or columns should resize to allow all text to be seen.

### Screenshots

Full screen
<img width="1903" alt="Screen Shot 2021-05-07 at 10 29 40 AM" src="https://user-images.githubusercontent.com/17128960/118191174-09592d80-b3f9-11eb-844e-9a93c3167616.png">

50% screen width
<img width="1277" alt="Screen Shot 2021-05-07 at 10 29 31 AM" src="https://user-images.githubusercontent.com/17128960/118191221-1bd36700-b3f9-11eb-828d-4a4eb7f15401.png">

### Additional context

When using a touchpad, it is possible to scroll to the right inside the middle column, allowing you to see the cutoff text. However, this is not something a user with a mouse could do.

**Comment by jpvajda** [comment] 2021-05-18 23:36
@wrekone I can't reproduce on Firefox or Chrome what browser did you happen to see this in?

**Comment by jpvajda** [comment] 2021-05-19 22:33
also tested firefox and I can't reproduce. so i'm going to close it until we know what browser this was in.

**Closed by jpvajda** 2021-05-19 22:33 UTC
Labels: bug, eng, question

**Comment by wrekone** [comment] 2021-05-20 02:57
This behavior was seen in Chrome 89.

I can no longer reproduce the behavior in Chrome  90.0.4430.212
