### ISSUE TITLE
A signficant amount of Console `GET` failures for page-data.json requests

### ISSUE THREAD

**Issue by zstix** [newrelic/docs-website#1874] opened 2021-04-16 21:05 UTC
### Steps to reproduce

`NOTE` This error happens intermittently on different pages It seems to be triggered when a user traverses the navigation

- Go to https://docs.newrelic.com/docs/telemetry-data-platform/ingest-manage-data/understand-data/new-relic-data-types/ 
- click on Query your Data in the right nave 
-  and review the console 
- See the errors for page-data.json

Go to  

- go to https://docs.newrelic.com/docs/agents/php-agent/getting-started/introduction-new-relic-php/
- click on New Relic for PHP in the right nav
- - See the errors for page-data.json

### Tell us what you need
When I scroll down the page on the "Introduction to New Relic for PHP" page, I see the following errors in my console:

![Screen Shot 2021-04-16 at 2 04 55 PM](https://user-images.githubusercontent.com/1946433/115083753-b99c4a80-9ebc-11eb-8dd3-b5f0eb1a10b0.png)

~~It's worth noting that this page gets a lot of traffic and causes a [significant amount](https://staging.one.nr/01qwL4L5bw5) of errors.~~

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/agents/php-agent/getting-started/introduction-new-relic-php/
* **OS**: MacOS
* **Browser**: Chrome 90
* **Device**: MacBook Pro

**Comment by zstix** [comment] 2021-04-16 21:06
@jpvajda Here's another one that's causing a lot of issues.

**Comment by roadlittledawn** [comment] 2021-04-19 18:34
FWIW: i see this error on most pages on the site

**Comment by roadlittledawn** [comment] 2021-04-19 18:38
Some potentially useful info in this thread: https://github.com/gatsbyjs/gatsby/issues/16097

**Comment by zstix** [comment] 2021-04-20 16:50
We decided to timebox an hour to look into this (and reach out to Gatsby about it). If this takes longer than that, we should re-estimate it and prioritize it for a later sprint.

**Comment by roadlittledawn** [comment] 2021-04-21 18:02
So far, it looks like this is expected behavior for Gatsby's pre-fetching page data for any links on a given page (was [added as a performance improvement](https://www.gatsbyjs.com/blog/2019-06-12-performance-improvements-for-large-sites/) to avoid a monolithic page manifest file on large sites). 

and so far it appears that 404s occur for links that are redirected to other pages. which would make sense that there's no page data for a given path that doesn't actually have content and instead redirects to one that does.

**Comment by jpvajda** [comment] 2021-04-21 18:24
This is seems to be happening on all or most pages... so do we need to actually create files for page-data.json requests? 

> Now, when a page navigation occurs, Gatsby makes a request directly to the server for the page-data.json, instead of checking the global manifest (which doesn't exist anymore).

<img width="1182" alt="Screen Shot 2021-04-21 at 12 22 04 PM" src="https://user-images.githubusercontent.com/1395158/115602753-867f0000-a29c-11eb-8851-88834bd794e9.png">

**Comment by roadlittledawn** [comment] 2021-04-21 18:32
> This is seems to be happening on all or most pages... so do we need to actually create files for page-data.json requests?
> 
> > Now, when a page navigation occurs, Gatsby makes a request directly to the server for the page-data.json, instead of checking the global manifest (which doesn't exist anymore).
> 
> <img alt="Screen Shot 2021-04-21 at 12 22 04 PM" width="1182" src="https://user-images.githubusercontent.com/1395158/115602753-867f0000-a29c-11eb-8851-88834bd794e9.png">

no, that's internal to how Gatsby does its thang

**Comment by jpvajda** [comment] 2021-04-23 00:10
@roadlittledawn  

> no, that's internal to how Gatsby does its thang

Not sure I follow, are you saying these errors are expected?

**Comment by jpvajda** [comment] 2021-04-24 16:53
I've asked Gatsby if this issue could be covered in our upcoming build audit.

**Comment by jpvajda** [comment] 2021-04-26 23:11
It sounds like this may be covered in our Build Audit.

**Comment by roadlittledawn** [comment] 2021-05-11 18:10
It seems you can disable prefetching, but not sure what the performance tradeoff there would be.

Also, seems like [others have used `@reach/router`](https://github.com/gatsbyjs/gatsby/issues/14016#issuecomment-491999391) for links to optionally avoid prefetching, but that would require knowing a given link is actually a redirect before rendering either the Gatsby `<Link />` or using `@reach/router`.

**Comment by jpvajda** [comment] 2021-05-13 18:59
Gatsby has an open PR for this issue: https://github.com/gatsbyjs/gatsby/pull/31366

**Comment by rudouglas** [comment] 2021-05-19 12:08
@jpvajda that PR has been merged and waiting to be pulled into a release, should we put this in blocked until then? 
https://github.com/gatsbyjs/gatsby/pull/31480

**Comment by pieh** [comment] 2021-05-19 16:41
I opened https://github.com/newrelic/docs-website/pull/2357 which bump gatsby to newly released version that takes care of links to redirected pages that with current version are causing 404 responses (it doesn't take care of all 404 instances, as I mentioned in the PR nothing 2 instances of 404s that are still there on sample page I was checking)

**Comment by jpvajda** [comment] 2021-05-19 17:13
@rudouglas Yes, we can mark it as blocked until a new version of Gatsby is release and we can upgrade to it. Thanks for the fix @pieh we appreciate! ❤️

**Closed** 2021-05-24 19:06 UTC
Labels: P2, bug, build audit, eng, gatsbysites, hero, sp:2
