### ISSUE TITLE
[Gatsby Cloud] Deployment issue for docs-websites -  redirect limits exceeded ETA JULY

### ISSUE THREAD

**Issue by nr-kkenney** [newrelic/docs-website#2477] opened 2021-05-26 17:23 UTC
> This currently is blocking us from moving the Docs site to Gatsby Cloud

### Background

we noticed our deploys for docs-website & docs-website-develop production branches are running into an issue on Gatsby Cloud deployment:
>Deploy Error from Gatsby Hosting: Unable to set vcl configuration. Snippet is too long. It must be less than 1000000 bytes.

we assume this is related to the size of our repo & artifacts. is there anything we can do on our end to resolve this? :see_no_evil:

example failure: 
![Screen Shot 2021-05-24 at 9 52 16 AM](https://user-images.githubusercontent.com/70179215/119704567-a5793080-be0c-11eb-9a32-fdddd11c056a.png)

### Gatsby Notes

likely caused by redirects exceeded 5k, we currently have 10k - 16k redirects which may be causing this. Gatsby said in June they'd have a fix in place in June that may resolve this. 

Gatsby Zendesk `14687`

### Acceptance Criteria
- [x] Confirm with Gatsby the ETA on this fix, if it's really June - @jpvajda 
- [x] Confirm how many redirects do we have in total?
- [x]  Confirm if we have duplicates,  if so, how many?
- [x] When we add a new language site we 2x these redirects every time.  Do we really need the redirects on the translated pages?
- [x] Confirm if we actually need so many redirects. why is that a requirements? - @jpvajda 
- [x] confirm fix is in place by Gatsby 
- [x] builds succeed on Gatsby cloud and excessive redirects no longer cause build failures

**Comment by nr-kkenney** [comment] 2021-05-26 18:56
picking up this ticket to try and answer these questions:
- [ ] how many redirects do we have in total?
- [ ] do we have duplicates? if so, how many?

**Comment by nr-kkenney** [comment] 2021-05-26 21:40
here is the script i came up with: https://gist.github.com/nr-kkenney/00aa616813ef15da522ac7a93d1046e1

the important output:
```sh
Number of redirects in GraphQL: 6758
Number of redirects in taxonomy-redirect.json: 800
Total number of redirects: 7558
Total number of duplicates: 267
```

which i believe is just for english. so we would multiply that value for each non-english language we have / add.

**Comment by nr-kkenney** [comment] 2021-05-26 21:49
in terms of a next step, i see the following as options:
1. do nothing. we wait for gatsby to implement their solution which they said should be ready late june / early july. the solution will make the current problem we are running into (5000 limit) obsolete, so any number of redirects should work once its in place.
2. remove (some) redirects. if we want to migrate docs-website to gatsby cloud before their solution to this problem is out, we need to reduce the total number of redirects across all locales below 5000. this can probably have many different outcomes in terms of what stays and what remains depending on opinions.

@jpvajda i defer to you and your judgement for what should happen next 🙈

**Comment by roadlittledawn** [comment] 2021-05-26 22:45
awesome to see this quntified!

and that looks like it's just redirects from `.mdx` frontmatter and `taxonomy-redirects.json` right?

in addition to adding redirects 1:1 for `/jp/` pages like you mentioned,  i think we also programmatically redirect for special cases in some `gatsby-node.js` files that may not be covered in those two files. one example is redirects to account for old URL pattern of What's New posts vs our new URL pattern. we also add redirects for most current agent release note page at `.../AGENT_NAME/current`. and looks like there are some redirects  we apply for attribute definitions as well (which if i recall correctly were about 900+ files when we migrated.

**Comment by jpvajda** [comment] 2021-05-26 23:45
I'd suggest we work to get the redirects down to an acceptable limit, <5000 so we can continue with the migration and not wait for Gatsby, as it's possible they may have a delay in resolving this. Though to do that we'd have to work with @austin-schaefer on this and he'd have to be willing to reduce our total redirect count to the limits Gatsby is currently enforcing.  

Overall even if Gatsby had no limits on redirects I think it be wise for us to establish a redirect cleanliness approach so we aren't creating thousands of redirects unnecessarily.

so next steps would be to discuss with Austin to present him with this current limitation, --> I'll take that.

**Comment by austin-schaefer** [comment] 2021-05-27 16:00
I'm fine reducing but I'd like to be confident we're not breaking too many users' experiences. @roadlittledawn @jpvajda do we have usage data for redirects in Gatsby? If not, can we use the data from the old Drupal site? I'm fine killing low-traffic redirects with, asy, less than 15 total hits. I don't want to kill redirects getting hundreds or thousands of uses.

**Comment by austin-schaefer** [comment] 2021-05-27 16:01
@jpvajda : 

> Overall even if Gatsby had no limits on redirects I think it be wise for us to establish a redirect cleanliness approach so we aren't creating thousands of redirects unnecessarily.

FWIW these redirects are not being created unnecessarily. Historically we created a redirect every time a doc moves. This ensures we don't break links for our customers. It helps with SEO. It also simplifies the work of editing the site, because there's not a decision on _whether_ to redirect.

**Comment by zstix** [comment] 2021-05-27 16:51
There are a couple of options moving forward:

1. Wait until Gatsby supports our need for this many redirects (stay on Amplify until sometime in June)
2. Remove some redirects and migrate to Gatsby now (and potentially add them back later)

It seems like we have to wait on the fix from Gatsby.

**Comment by austin-schaefer** [comment] 2021-05-27 16:55
@zstix If it's only till June, I'd be inclined to wait it out. As I said I'm fine trimming the list, but it would definitely require some digging around to figure out what we can safely remove (and then some kind of automation to remove those under-used redirects)

We have a heck of a big Gatsby site. :)

**Comment by nr-kkenney** [comment] 2021-05-27 16:57
given clinton's comment, i made a second attempt at better getting the redirect count. for this approach, i just counted the usage of `createRedirect`, and for this approach the data is:

```none
Total redirect count (for all locales): 17924
Duplicate count: 2228
```

**Comment by zstix** [comment] 2021-05-27 17:01
I'm going to move this out of this sprint and lower the severity level since it sounds like the best action is no action (until the new platform supports our use case). Thanks all the work on this stuff!!

**Comment by nr-kkenney** [comment] 2021-05-27 18:19
this is the ticket for gatsby's solution: https://portal.gatsbyjs.com/gatsby-cloud/p/allow-for-unlimited-redirects we can use to follow their progress.

**Comment by jpvajda** [comment] 2021-06-01 15:25
According to Generosa, after Gatsby does their fix for this problem, there are no limits to consider.

**Comment by jpvajda** [comment] 2021-06-07 22:12
ETA for this fix by Gatsby is Late July / Aug

**Comment by jpvajda** [comment] 2021-07-09 17:25
Gatsby confirmed this functionality is now available, they will enable our develop and main sites on Gatsby Cloud for testing.

**Comment by jpvajda** [comment] 2021-07-12 20:29
Gatsby has migrated the Develop and Main sites to hosting V2.   You will see that the Gatsby Cloud domain to include .routing-gatsbyjs.io

**Comment by jpvajda** [comment] 2021-07-12 21:15
2 builds have passed all checks an successfully built the site post migration, so i think this is good to go. 

<img width="1245" alt="Screen Shot 2021-07-12 at 3 13 40 PM" src="https://user-images.githubusercontent.com/1395158/125356814-f93fca80-e323-11eb-920a-d149629810ab.png">
<img width="1240" alt="Screen Shot 2021-07-12 at 3 13 25 PM" src="https://user-images.githubusercontent.com/1395158/125356816-f9d86100-e323-11eb-8b81-35ac7094ced8.png">

**Closed** 2021-07-12 21:18 UTC
Labels: docs-liaison, gatsbysites, sp:1
