### ISSUE TITLE
Kafka monitoring pages did not migrate correctly

### ISSUE THREAD

**Issue by zstix** [newrelic/docs-website#1123] opened 2021-03-03 17:51 UTC
(rewritten by Austin)

This doc was in the manual-edits folder, which has caused the migration script to behave a bit weirdly. Two clamshells ("JMX connection errors" and "Kerberos authentication failing") went missing. Compare:

* Actual: https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/kafka-monitoring-integration
* Expected version (on old Drupal site): https://docs-dev.newrelic.com/docs/integrations/host-integrations/host-integrations-list/kafka-monitoring-integration

This doc was also in the manual edits folder, and may have issues too

* https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-serverless-monitoring-aws-lambda-legacy/

## Action items

1. Compare the docs.newrelic.com and docs-dev.newrelic.com versions of:
    * https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-serverless-monitoring-aws-lambda-legacy/
    * https://docs-dev.newrelic.com/docs/integrations/host-integrations/host-integrations-list/kafka-monitoring-integration
2. Look for any issues or missing content
3. If you find any, manually fix the docs

**Comment by austin-schaefer** [comment] 2021-03-03 17:53
@zstix : One element I'd like to add here is a "root cause analysis" of sorts. I just want to make sure we understand why this happened so we can see if other docs might have been effected.

**Comment by jpvajda** [comment] 2021-03-09 21:51
we could rerun the migration script on this or just manually add the missing content. It's probably easier to fix this as content change vs. trying to spend engineering effort on re-running our script. @austin-schaefer - let me know what you think

**Comment by austin-schaefer** [comment] 2021-03-09 23:21
@jpvajda I'm not too worried about the missing content—it's easy enough to manually restore. As I mentioned in a comment up-thread, I'm more concerned about understanding _why_ this happened and if it could have happened elsewhere. Was this a one-off, or are there other docs that are missing content?

**Comment by jpvajda** [comment] 2021-03-09 23:47
@austin-schaefer we believe it be a one off.

**Comment by austin-schaefer** [comment] 2021-03-09 23:49
@jpvajda : Can you share more on why we're confident it was a one-off?

**Comment by roadlittledawn** [comment] 2021-03-10 00:43
i believe the kafka monitoring integration was in the `manual-edits` folder so it was likley old content that was never updated before final migration.

**Comment by jpvajda** [comment] 2021-03-10 19:46
@austin-schaefer i'll close this if you are ok correcting manually or you can move it your content board.

**Comment by austin-schaefer** [comment] 2021-03-10 22:52
Sure, let's move to content board and re-scope to also look at this doc @roadlittledawn shared

> src/manual-edits/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-serverless-monitoring-aws-lambda-legacy.mdx

**Comment by paperclypse** [comment] 2021-03-15 23:58
The two version match for https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-serverless-monitoring-aws-lambda-legacy/.

However, there are some discrepancies between the two Kafka monitoring versions.

@rhetoric101: Is this the most up-to-date version of this doc? https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/kafka-monitoring-integration/

**Comment by roobre** [comment] 2021-03-16 11:02
Hey, this is Roberto from Core Integrations, I was the main contributor to the last big change for the Kafka page. I can confirm the [current version](https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/kafka-monitoring-integration/) is not up to date.

We put quite the effort in this particular page, and clients misconfiguring this integration is a known source of problems for us. It would be awesome if you could keep me posted about any news about this!

**Comment by rhetoric101** [comment] 2021-03-19 17:35
I just merged my changes into develop to restore that missing "preparation" section (https://github.com/newrelic/docs-website/pull/1388)

**Comment by roobre** [comment] 2021-03-22 15:17
Awesome, thank you very much!

**Comment by paperclypse** [comment] 2021-03-25 21:02
@austin-schaefer It looks like we've addressed the Action Items listed in the issue description. Can we close this issue or should we keep it open?

**Comment by austin-schaefer** [comment] 2021-03-26 01:38
Let’s close it!


________________________________

**Comment by gsanchezgavier** [comment] 2021-03-26 08:27
Hey Guillermo here from Coreint team too. I just check that the doc has some missing troubleshooting step.
Here is a copy of the Google's cache i took a few weeks ago.
https://docs.google.com/document/d/1A5xyDMe9I8dKKJx6goU_AWp7CKsvr6mvsh6vbcNl26c/edit
Could you add that too? Thanks

**Comment by rhetoric101** [comment] 2021-03-26 16:41
@gsanchezgavier, thanks for pointing out that the new troubleshooting information didn't make it through the migration either. Just to confirm, we are just adding that collapser section titled "JMX connection errors," right?

**Comment by gsanchezgavier** [comment] 2021-03-30 08:24
Hi @rhetoric101  , yes that is it thanks

> Just to confirm, are we just adding back the collapser sections "JMX connection errors" and "Kerberos authentication failing"?

**Closed** 2021-03-31 16:37 UTC
Labels: P3, bug, content
